name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Sudeep"
      - name: Multiline Command
        run: |
          node -v
          npm -v